# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: "Continuous Integration"

on:
  push:
    branches: 
      - "**"

  pull_request:
    branches: 
      - "**"

jobs:
  build:
    name: Build library

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "../TestResults"
      working-directory: ./src

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-test-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

  build-samples:
    name: Build Samples

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore samples.sln
      working-directory: ./samples

    - name: Build
      run: dotnet build --no-restore samples.sln
      working-directory: ./samples

  build-samples-osx:
    name: Build OS X Samples

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore workloads
      run: sudo dotnet workload restore samples-osx.sln
      working-directory: ./samples

    - name: Restore dependencies
      run: dotnet restore samples-osx.sln
      working-directory: ./samples


    - name: Build
      run: dotnet build --no-restore samples-osx.sln
      working-directory: ./samples
