# yamllint disable rule:line-length
# deployes the build to nuget and github releases
name: Manually deploy docs

concurrency:
  group: "deployment"
  cancel-in-progress: false

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write

on: workflow_dispatch

jobs:
  publish-docs:
    uses: ./.github/workflows/deploy_docs_job.yml
